name: CI
on:
  push:
    branches:
      - my-main

jobs:
  build:
    if: github.repository == 'k23223/reference'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: dist/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Modify CONTRIBUTING.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: CONTRIBUTING.md
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: gh-pages README.md
        working-directory: dist
        run: |
          cat << "EOF" > README.md
          Website: https://www.xpctf.cn/reference/
          ## Docker

          [![Docker Image Version (latest by date)](https://img.shields.io/docker/v/wcjiang/reference)](https://hub.docker.com/r/wcjiang/reference) [![Docker Image Size (latest by date)](https://img.shields.io/docker/image-size/wcjiang/reference)](https://hub.docker.com/r/wcjiang/reference) [![Docker Pulls](https://img.shields.io/docker/pulls/wcjiang/reference)](https://hub.docker.com/r/wcjiang/reference)

          轻松通过 `docker` 部署 `Quick Reference` 网站。

          ```bash
          docker pull wcjiang/reference
          ```

          ```bash
          docker run --name reference --rm -d -p 9667:3000 wcjiang/reference:latest
          # Or
          docker run --name reference -itd -p 9667:3000 wcjiang/reference:latest
          ```

          在浏览器中访问以下 URL

          ```bash
          http://localhost:9667/
          ```
          EOF

      - name: gh-pages .env
        working-directory: dist
        run: |
          cat << "EOF" > .env
          REF_URL=https://www.xpctf.cn/reference/
          REF_LABEL=网站首页
          LICENSE=Copyright (c) <b>2023</b> 一只小白™
          EOF

      - name: gh-pages .gitignore
        working-directory: dist
        run: |
          cat << "EOF" > .gitignore
          node_modules
          .husky
          .github
          pnpm-lock.yaml
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
